apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-service
  namespace: default
  labels:
    app: catalog-service
    company: carvedrock
spec:
  replicas: 2
  selector:
    matchLabels:
      app: catalog-service
  template:
    metadata:
      labels:
        app: catalog-service
        version: "1.0.0"
    spec:
      containers:
      - name: catalog
        image: nginx:1.19
        ports:
        - containerPort: 80
          name: http
        env:
        - name: VERSION
          value: "1.0.0"
        - name: CATALOG_NAME
          value: "CarvedRock Outdoor Gear"
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
