apiVersion: v1
kind: Service
metadata:
  name: catalog-service
  namespace: default
  labels:
    app: catalog-service
    company: carvedrock
spec:
  type: ClusterIP
  selector:
    app: catalog-service
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
